// ==========================================
// ShopEasy POS v2 — Configuration
// Industry definitions, translations, defaults
// ==========================================

export const INDUSTRIES = {
  kirana: {
    id: 'kirana',
    name: 'Kirana / General Store',
    icon: '🏪',
    description: 'Grocery, daily essentials, inventory management',
    color: '#0D9488',
    features: ['billing', 'inventory', 'khata', 'reports'],
    tabs: ['billing', 'inventory', 'khata', 'reports'],
    defaultCategories: ['Grocery', 'FMCG', 'Snacks', 'Dairy', 'Beverages', 'Other'],
    productFields: ['name', 'price', 'stock', 'unit', 'category', 'gst'],
    sampleProducts: [
      { id: 'p1', name: 'Toor Dal', price: 140, stock: 25, unit: 'kg', category: 'Grocery', gst: 5 },
      { id: 'p2', name: 'Basmati Rice', price: 95, stock: 50, unit: 'kg', category: 'Grocery', gst: 5 },
      { id: 'p3', name: 'Sunflower Oil', price: 180, stock: 12, unit: 'L', category: 'Grocery', gst: 5 },
      { id: 'p4', name: 'Sugar', price: 45, stock: 40, unit: 'kg', category: 'Grocery', gst: 5 },
    ],
  },
  restaurant: {
    id: 'restaurant',
    name: 'Restaurant / Cafe',
    icon: '🍽️',
    description: 'Dine-in, takeout, table management, orders',
    color: '#E85D25',
    features: ['billing', 'orders', 'tables', 'khata', 'reports'],
    tabs: ['billing', 'orders', 'tables', 'khata', 'reports'],
    defaultCategories: ['Starters', 'Main Course', 'Desserts', 'Beverages', 'Snacks'],
    productFields: ['name', 'price', 'category', 'prep_time'],
    sampleProducts: [
      { id: 'p1', name: 'Butter Chicken', price: 350, category: 'Main Course', prep_time: 20 },
      { id: 'p2', name: 'Samosa', price: 30, category: 'Snacks', prep_time: 5 },
      { id: 'p3', name: 'Biryani', price: 250, category: 'Main Course', prep_time: 25 },
    ],
  },
  cloth: {
    id: 'cloth',
    name: 'Clothing Boutique',
    icon: '👕',
    description: 'Size/color variants, fitting rooms, inventory by size',
    color: '#9333EA',
    features: ['billing', 'inventory', 'variants', 'khata', 'reports'],
    tabs: ['billing', 'inventory', 'variants', 'khata', 'reports'],
    defaultCategories: ['Men', 'Women', 'Kids', 'Accessories'],
    productFields: ['name', 'price', 'category', 'sizes', 'colors'],
    sampleProducts: [
      { id: 'p1', name: 'Cotton T-Shirt', price: 399, category: 'Men', sizes: ['S', 'M', 'L', 'XL'], colors: ['Blue', 'Red', 'Black'] },
      { id: 'p2', name: 'Jeans', price: 999, category: 'Men', sizes: ['28', '30', '32', '34', '36'], colors: ['Blue', 'Black'] },
    ],
  },
  tiffin: {
    id: 'tiffin',
    name: 'Tiffin / Food Service',
    icon: '🍱',
    description: 'Meal plans, subscriptions, delivery tracking',
    color: '#D97706',
    features: ['billing', 'subscriptions', 'delivery', 'khata', 'reports'],
    tabs: ['billing', 'subscriptions', 'delivery', 'khata', 'reports'],
    defaultCategories: ['Breakfast', 'Lunch', 'Dinner', 'Snacks', 'Combos'],
    productFields: ['name', 'price', 'serving_size', 'daily_quota'],
    sampleProducts: [
      { id: 'p1', name: 'Lunch Meal', price: 200, serving_size: '2 person', daily_quota: 50 },
      { id: 'p2', name: 'Breakfast', price: 120, serving_size: '1 person', daily_quota: 30 },
      { id: 'p3', name: 'Dinner Combo', price: 250, serving_size: '2 person', daily_quota: 40 },
    ],
  },
  pharmacy: {
    id: 'pharmacy',
    name: 'Pharmacy',
    icon: '💊',
    description: 'Medicine inventory, batch/expiry tracking, prescriptions',
    color: '#059669',
    features: ['billing', 'inventory', 'khata', 'reports'],
    tabs: ['billing', 'inventory', 'khata', 'reports'],
    defaultCategories: ['Tablets', 'Capsules', 'Syrups', 'Ointments', 'Supplements'],
    productFields: ['name', 'price', 'batch_number', 'expiry_date', 'stock'],
    sampleProducts: [
      { id: 'p1', name: 'Aspirin 500mg', price: 20, batch: 'BATCH001', expiry: '2026-12-31', stock: 100 },
      { id: 'p2', name: 'Cough Syrup', price: 150, batch: 'BATCH002', expiry: '2026-10-15', stock: 25 },
    ],
  },
  salon: {
    id: 'salon',
    name: 'Salon / Spa',
    icon: '💇',
    description: 'Service booking, staff management, appointments',
    color: '#DC2626',
    features: ['billing', 'appointments', 'staff', 'khata', 'reports'],
    tabs: ['billing', 'appointments', 'staff', 'khata', 'reports'],
    defaultCategories: ['Hair', 'Skin', 'Nails', 'Packages'],
    productFields: ['name', 'price', 'duration_minutes', 'staff_required'],
    sampleProducts: [
      { id: 'p1', name: 'Haircut', price: 300, duration: 30, staff: 'Barber' },
      { id: 'p2', name: 'Facial', price: 500, duration: 60, staff: 'Therapist' },
      { id: 'p3', name: 'Massage', price: 800, duration: 90, staff: 'Therapist' },
    ],
  },
};

export const TRANSLATIONS = {
  en: {
    welcome: 'Welcome to ShopEasy POS',
    selectIndustry: 'What type of business are you running?',
    startUsing: 'Start Using ShopEasy',
    setupShop: 'Setup Your Shop',
    billing: 'Billing',
    inventory: 'Inventory',
    khata: 'Khata',
    orders: 'Orders',
    tables: 'Tables',
    subscriptions: 'Subscriptions',
    staff: 'Staff',
    variants: 'Variants',
    appointments: 'Appointments',
    delivery: 'Delivery',
    reports: 'Reports',
    settings: 'Settings',
    search: 'Search products or scan barcode...',
    cart: 'Current Bill',
    qty: 'Qty',
    price: 'Price',
    amount: 'Amount',
    product: 'Product',
    unit: 'Unit',
    category: 'Category',
    addToCart: 'Add',
    removeItem: 'Remove',
    clearCart: 'Clear Cart',
    subtotal: 'Subtotal',
    gst: 'GST',
    discount: 'Discount',
    grandTotal: 'Grand Total',
    total: 'Total',
    pay: 'Cash / UPI',
    credit: 'Khata',
    printBill: 'Print Bill',
    stock: 'Stock',
    lowStockAlerts: 'Low Stock Alerts',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete',
    productName: 'Product Name',
    sellingPrice: 'Selling Price',
    costPrice: 'Cost Price',
    stockQty: 'Stock Quantity',
    lowStockAt: 'Low Stock Alert At',
    save: 'Save',
    cancel: 'Cancel',
    customer: 'Customer',
    phone: 'Phone',
    balance: 'Credit Balance',
    lastVisit: 'Last Visit',
    totalOutstanding: 'Total Outstanding Credit',
    customersWithCredit: 'customers with pending credit',
    noPending: 'No pending credit',
    recordPayment: 'Record Payment',
    markPaid: 'Mark as Paid',
    enterAmount: 'Enter amount',
    paymentRecorded: 'Payment Recorded!',
    sendReminder: 'Send WhatsApp Reminder',
    addCustomer: 'Add Customer',
    dailySummary: "Today's Summary",
    totalSales: 'Total Sales',
    totalBills: 'Bills',
    cashCollected: 'Cash Collected',
    creditGiven: 'Credit Given',
    profit: 'Est. Profit',
    topProducts: 'Top Selling Products',
    billHistory: 'Recent Bills',
    shopName: 'Shop Name',
    ownerName: 'Owner Name',
    address: 'Address',
    gstNumber: 'GST Number',
    language: 'Language',
    changeIndustry: 'Change Business Type',
    getStarted: 'Get Started',
    selectLanguage: 'Select Language',
    logout: 'Logout',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    update: 'Update',
    close: 'Close',
    savedSuccess: 'Saved!',
    paymentSuccess: 'Payment Successful!',
    khataSuccess: 'Added to Khata!',
    errorOccurred: 'Error occurred. Please try again.',
    noProducts: 'No products found',
    noData: 'No data yet. Start billing!',
  },
  te: {
    welcome: 'ShopEasy POS కి స్వాగతం',
    selectIndustry: 'మీరు ఏ రకమైన వ్యాపారం చేస్తున్నారు?',
    startUsing: 'ShopEasy ఉపయోగించటం ప్రారంభించండి',
    setupShop: 'మీ దుకాణం సెటప్ చేయండి',
    billing: 'బిల్లింగ్',
    inventory: 'ఇన్వెంటరీ',
    khata: 'ఖాతా',
    orders: 'ఆర్డర్లు',
    tables: 'టేబుల్‌లు',
    subscriptions: 'సబ్‌స్క్రిప్షన్‌లు',
    reports: 'రిపోర్టులు',
    search: 'ఉత్పత్తులు వెతకండి...',
    cart: 'ప్రస్తుత బిల్లు',
    qty: 'పరిమాణం',
    price: 'ధర',
    product: 'ఉత్పత్తి',
    unit: 'యూనిట్',
    category: 'వర్గం',
    subtotal: 'సబ్‌టోటల్',
    gst: 'జిఎస్టీ',
    grandTotal: 'గ్రాండ్ టోటల్',
    total: 'మొత్తం',
    pay: 'నగదు / UPI',
    credit: 'ఖాతా',
    customer: 'కస్టమర్',
    phone: 'ఫోన్',
    balance: 'అరువు బ్యాలన్స్',
    recordPayment: 'చెల్లింపు నమోదు చేయండి',
    totalSales: 'మొత్తం అమ్మకాలు',
    totalBills: 'బిల్లులు',
    cashCollected: 'నగదు సేకరించారు',
    creditGiven: 'ఖాతా ఇచ్చారు',
    shopName: 'దుకాణం పేరు',
    ownerName: 'యజమాని పేరు',
    address: 'చిరునామా',
    language: 'భాష',
    getStarted: 'ప్రారంభించండి',
    save: 'సేవ్',
    cancel: 'రద్దు',
    submit: 'సమర్పించండు',
  },
};

export const DEFAULT_SETTINGS = {
  currency: 'INR',
  timezone: 'Asia/Kolkata',
  dateFormat: 'DD/MM/YYYY',
  language: 'en',
  gstEnabled: true,
  defaultGstRate: 5,
  billPrefix: 'BILL',
  printReceipt: true,
};

export const PAYMENT_MODES = ['cash', 'upi', 'card', 'credit', 'cheque'];
export const ORDER_STATUSES = ['pending', 'preparing', 'ready', 'served', 'cancelled'];
export const SUBSCRIPTION_TYPES = ['5-day', '10-day', 'monthly', 'custom'];
export const STAFF_ROLES = ['owner', 'manager', 'cashier', 'chef', 'waiter', 'delivery', 'therapist'];
